//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef NF_TWAI_H
#define NF_TWAI_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

typedef enum __nfpack TWAIMode
{
    TWAIMode_TWAI_MODE_NORMAL = 0,
    TWAIMode_TWAI_MODE_NO_ACK = 1,
    TWAIMode_TWAI_MODE_LISTEN_ONLY = 2,
} TWAIMode;

struct Library_NF_TWAI_NF_TWAI_TWAI
{
    NANOCLR_NATIVE_DECLARE(NativeTwaiInstall___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(NativeTwaiUninstall___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(NativeTwaiStart___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(NativeTwaiStop___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(NativeTwaiX___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(NativeTwaiY___STATIC__I4);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_TWAI;

#endif // NF_TWAI_H
