//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "NF_TWAI.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_NF_TWAI_NF_TWAI_TWAI::NativeTwaiInstall___STATIC__I4,
    Library_NF_TWAI_NF_TWAI_TWAI::NativeTwaiUninstall___STATIC__I4,
    Library_NF_TWAI_NF_TWAI_TWAI::NativeTwaiStart___STATIC__I4,
    Library_NF_TWAI_NF_TWAI_TWAI::NativeTwaiStop___STATIC__I4,
    Library_NF_TWAI_NF_TWAI_TWAI::NativeTwaiX___STATIC__I4,
    Library_NF_TWAI_NF_TWAI_TWAI::NativeTwaiY___STATIC__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_TWAI =
{
    "NF.TWAI",
    0x6483352C,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
